# coding: UTF-8

require 'csv'   

if AdminUser.count == 0
  AdminUser.create(email:"admin@example.com", password:"password")
end

if Exchange.count == 0
  exchange = Exchange.create(title:"NASDAQ (США)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "nasdaq.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end

  exchange = Exchange.create(title:"FTSE 100 (Великобритания)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "ftse.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end
  
  exchange = Exchange.create(title:"DAX (Германия)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "dax.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end

  exchange = Exchange.create(title:"Nikkei 225 (Япония)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "nikkei.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end

  exchange = Exchange.create(title:"Hang-Seng (Гонконг)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "hang-seng.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end

  exchange = Exchange.create(title:"RTS (Россия)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "rts.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end

  exchange = Exchange.create(title:"KASE (Казахстан)")
  csv = CSV.parse(File.read([Rails.root.to_s, "db", "seeds", "kase.csv"].join("/")), :headers => true)  
  csv.each do |row|
    row = row.to_s.split(",")
    Indication.create(exchange:exchange, date:row[0], opening_value:row[1], current_value:row[4], min_value:row[3], max_value:row[2])    
  end
end

if Finance.count == 0
  fin = Finance.create(title:"Денежные средства в иностранной валюте в кассе", type_id:1)  
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)    
  fin = Finance.create(title:"Золото",type_id:1)    
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:30)      
  fin = Finance.create(title:"Счета и депозиты в банках и прочих финансовых институтах",type_id:1)      
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:30)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:30)      
  fin = Finance.create(title:"Финансовые инстументы, оцениваемые по справедливой стоимости, изменение которой отражается в составе прибыли или убыли за период",type_id:1)      
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:35)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)      
  fin = Finance.create(title:"Сделки «обратного «РЕПО»",type_id:1)   
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)       
  fin = Finance.create(title:"Финансовые активы, имеющиеся в наличии для продажи",type_id:1)      
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)       
  fin = Finance.create(title:"Инвестиции, удерживаемые до погашения",type_id:1)          
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:50)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:40)      
  fin = Finance.create(title:"Основные средства и нематериальные активы",type_id:1)   
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:30)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)      
  fin = Finance.create(title:"Прочие активы",type_id:1)         
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)             
    
  fin = Finance.create(title:"Деньги в обращении",type_id:2)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)      
  fin = Finance.create(title:"Средства банков и прочих финансовых институтов",type_id:2)  
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  fin = Finance.create(title:"Финансовые инстументы, оцениваемые по справедливой стоимости, изменение которой отражается в составе прибыли или убыли за период",type_id:2)    
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:15)        
  fin = Finance.create(title:"Текущие счета Национального Фонда Республики Казахстан",type_id:2)    
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  fin = Finance.create(title:"Текущие счета Министерства финансов Республики Казахстан",type_id:2) 
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:15)             
  fin = Finance.create(title:"Счета клиентов",type_id:2)   
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)             
  fin = Finance.create(title:"Долговые ценные бумаги выпущенные",type_id:2)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  fin = Finance.create(title:"Прочие активы",type_id:2)  
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  
  fin = Finance.create(title:"Уставной капитал",type_id:3) 
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)         
  fin = Finance.create(title:"Резервный капитал",type_id:3)   
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)         
  fin = Finance.create(title:"Резерв переоценки инвестиций, имеющихся в наличии для продажи",type_id:3)    
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  fin = Finance.create(title:"Резерв переоценки иностранной валюты и аффинированных драгоценных металлов",type_id:3)      
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)        
  fin = Finance.create(title:"Резерв переоценки основных средств",type_id:3)      
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)        
  fin = Finance.create(title:"Нераспределенный прибыль",type_id:3)   
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:10)      
  
  mb = MiscBlock.create(screen_id:2, title:"Активы")
  MiscElem.create(misc_block:mb, title:"Монетарные деятельность", value:75, color:"79c999")
  MiscElem.create(misc_block:mb, title:"Немонетарные деятельность", value:25, color:"352dc9")  

  mb = MiscBlock.create(screen_id:2, title:"Обязательства")
  MiscElem.create(misc_block:mb, title:"Монетарные деятельность", value:65, color:"9d3ead")
  MiscElem.create(misc_block:mb, title:"Немонетарные деятельность", value:35, color:"68af53")  

  mb = MiscBlock.create(screen_id:2, title:"Капитал")
  MiscElem.create(misc_block:mb, title:"Монетарные деятельность", value:80, color:"a0f9d1")
  MiscElem.create(misc_block:mb, title:"Немонетарные деятельность", value:20, color:"b3b3b3")    
  
  fin = Finance.create(title:"Процентные доходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)      
  fin = Finance.create(title:"Процентные расходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:30)      
  fin = Finance.create(bold:true, title:"Чистый процентный доход до формирования резервов под обесценение активов, по которым начисляются проценты",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:35)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:35)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:50)      
  fin = Finance.create(title:"Комиссионные доходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:60)      
  fin = Finance.create(title:"Комиссионные расходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:40)      
  fin = Finance.create(bold:true, title:"Чистый комиссионный доход (убыток)",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:40)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:100)      
  fin = Finance.create(title:"Чистая прибыль от операций с финансовыми инструментами по справедливой стоимости через прибыль или убыток",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:60)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)      
  fin = Finance.create(title:"Чистый прибыль/(убыток) от операций с финансовыми активами, имеющимися в наличии для продажи",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:20)      
  fin = Finance.create(title:"Прочие операционные доходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:20)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:60)      
  fin = Finance.create(bold:true, title:"Непроцентные доходы (убытки)",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:100)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:50)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:100)      
  fin = Finance.create(bold:true, title:"Операционные доходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:155)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:125)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:250)      
  fin = Finance.create(title:"Восстановление обесценения",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-10)      
  fin = Finance.create(title:"Расходы по выпуску банкнот и монет",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-30)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-30)      
  fin = Finance.create(title:"Финансирование сторонних организаций",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-20)      
  fin = Finance.create(title:"Расходы на персонал",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-10)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-10)      
  fin = Finance.create(title:"Амортизация и износ",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-20)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-10)      
  fin = Finance.create(title:"Прочие общие и административные расходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-15)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-15)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-45)        
  fin = Finance.create(bold:true, title:"Операционные расходы",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:-110)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:-95)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:-125)        
  fin = Finance.create(bold:true, title:"Чистая прибыль",type_id:4)
  FinanceIndication.create(finance:fin, date:"2014-12-31", value:45)
  FinanceIndication.create(finance:fin, date:"2015-03-31", value:35)
  FinanceIndication.create(finance:fin, date:"2015-04-30", value:125)        
  
  mb = MiscBlock.create(screen_id:3, title:"Доход")
  MiscElem.create(misc_block:mb, title:"2014", value:65, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"2015", value:70, color:"27ae61")  

  mb = MiscBlock.create(screen_id:3, title:"Расход")
  MiscElem.create(misc_block:mb, title:"2014", value:75, color:"d25400")
  MiscElem.create(misc_block:mb, title:"2015", value:50, color:"d25400")  

  mb = MiscBlock.create(screen_id:3, title:"Капитал")
  MiscElem.create(misc_block:mb, title:"2014", value:40, color:"297fb9")
  MiscElem.create(misc_block:mb, title:"2015", value:65, color:"297fb9")  
  
  mb = MiscBlock.create(screen_id:4, title:"Карточек выпущено")
  MiscElem.create(misc_block:mb, title:"Иные", value:70, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"Кредитные", value:30, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:10, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"Иные", value:70, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"Кредитные", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:30, color:"3598db")    
  MiscElem.create(misc_block:mb, title:"Иные", value:70, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"Кредитные", value:45, color:"e77e23")
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:35, color:"3598db")     

  mb = MiscBlock.create(screen_id:4, title:"Держателей карточек")
  MiscElem.create(misc_block:mb, title:"Иные", value:60, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"Кредитные", value:20, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:10, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"Иные", value:62, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"Кредитные", value:30, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:30, color:"3598db")    
  MiscElem.create(misc_block:mb, title:"Иные", value:70, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"Кредитные", value:32, color:"e77e23")
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:35, color:"3598db")     

  mb = MiscBlock.create(screen_id:4, title:"Карточек использовано")
  MiscElem.create(misc_block:mb, title:"Иные", value:20, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"Кредитные", value:20, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:10, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"Иные", value:30, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"Кредитные", value:20, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:20, color:"3598db")    
  MiscElem.create(misc_block:mb, title:"Иные", value:33, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"Кредитные", value:24, color:"e77e23")
  MiscElem.create(misc_block:mb, title:"Дебетовые", value:25, color:"3598db")     

  mb = MiscBlock.create(screen_id:4, title:"Карточек использовано в разрезе карт")
  MiscElem.create(misc_block:mb, title:"Visa", value:30, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"MasterCard", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:35, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"MasterCard", value:70, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:38, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"MasterCard", value:74, color:"e77e23")

  mb = MiscBlock.create(screen_id:4, title:"Держателей карточек в разрезе карт")
  MiscElem.create(misc_block:mb, title:"Visa", value:30, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"MasterCard", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:35, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"MasterCard", value:70, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:38, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"MasterCard", value:74, color:"e77e23")

  mb = MiscBlock.create(screen_id:4, title:"Держателей карточек в разрезе карт")
  MiscElem.create(misc_block:mb, title:"Visa", value:30, color:"27ae61")
  MiscElem.create(misc_block:mb, title:"MasterCard", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:35, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"MasterCard", value:70, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Visa", value:38, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"MasterCard", value:74, color:"e77e23")

  mb = MiscBlock.create(screen_id:5, title:"POS-Терминалы")
  MiscElem.create(misc_block:mb, title:"В банках", value:30, color:"3598db")
  MiscElem.create(misc_block:mb, title:"В POS", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"В банках", value:35, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"В POS", value:70, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"В банках", value:38, color:"3598db")    
  MiscElem.create(misc_block:mb, title:"В POS", value:74, color:"e77e23")

  mb = MiscBlock.create(screen_id:5, title:"Импринтеров")
  MiscElem.create(misc_block:mb, title:"", value:10, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"", value:20, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"", value:22, color:"27ae61")

  mb = MiscBlock.create(screen_id:5, title:"Банкоматы")
  MiscElem.create(misc_block:mb, title:"Прием наличных", value:30, color:"3598db")
  MiscElem.create(misc_block:mb, title:"Обычный", value:40, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Прием наличных", value:35, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"Обычный", value:70, color:"e77e23")  
  MiscElem.create(misc_block:mb, title:"Прием наличных", value:38, color:"3598db")    
  MiscElem.create(misc_block:mb, title:"Обычный", value:74, color:"e77e23")

  mb = MiscBlock.create(screen_id:5, title:"Банковские киоски")
  MiscElem.create(misc_block:mb, title:"", value:30, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"", value:40, color:"27ae61")    
  MiscElem.create(misc_block:mb, title:"", value:42, color:"27ae61")

  mb = MiscBlock.create(screen_id:6, title:"Объем наличных денег национальной валюты в обращении")
  MiscElem.create(misc_block:mb, title:"Банкноты", value:40, color:"e77e23")      
  MiscElem.create(misc_block:mb, title:"Монеты", value:10, color:"3598db")  
  MiscElem.create(misc_block:mb, title:"Банкноты", value:50, color:"e77e23")        
  MiscElem.create(misc_block:mb, title:"Монеты", value:15, color:"3598db")  

  mb = MiscBlock.create(screen_id:6, title:"Банкноты по номиналам")
  MiscElem.create(misc_block:mb, title:"200 тенге", value:30, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"500 тенге", value:40, color:"e77e23")    
  MiscElem.create(misc_block:mb, title:"1 000 тенге (2006 г.)", value:60, color:"3598db")
  MiscElem.create(misc_block:mb, title:"1 000 тенге (Култегин)", value:60, color:"a34bd6")  
  MiscElem.create(misc_block:mb, title:"2 000 тенге", value:90, color:"ae2761")    
  MiscElem.create(misc_block:mb, title:"5 000 тенге", value:45, color:"23e77e")      
  MiscElem.create(misc_block:mb, title:"10 000 тенге", value:10, color:"db3598")      
  
  mb = MiscBlock.create(screen_id:6, title:"Монеты по номиналам")
  MiscElem.create(misc_block:mb, title:"1 тенге", value:30, color:"27ae61")  
  MiscElem.create(misc_block:mb, title:"2 тенге", value:40, color:"e77e23")    
  MiscElem.create(misc_block:mb, title:"5 тенге", value:42, color:"3598db")
  MiscElem.create(misc_block:mb, title:"10 тенге", value:30, color:"a34bd6")  
  MiscElem.create(misc_block:mb, title:"20 тенге", value:40, color:"ae2761")    
  MiscElem.create(misc_block:mb, title:"50 тенге", value:42, color:"23e77e")
  MiscElem.create(misc_block:mb, title:"100 тенге", value:30, color:"db3598")    
  
  
end

if CurrencyExchange.count == 0
  JSON.parse(File.read([Rails.root.to_s, "db", "seeds", "currency_seed.json"].join("/"))).each {|elem| CurrencyExchange.create(title:elem["title"], value:elem["value"], date:DateTime.parse(elem["date"])) }  
end

if Commodity.count == 0
  %w[aluminium copper gas gold oil platinum silver].each do |file|
    JSON.parse(File.read([Rails.root.to_s, "db", "seeds", "#{file}.json"].join("/")))["data"].each {|elem| Commodity.create(title:file.capitalize, value:elem[1], date:DateTime.parse(elem[0])) if DateTime.parse(elem[0]).year >= 2015}
  end
end